run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - .github

output:
  sort-results: true

linters:
  enable-all: true
  disable:
  # Remove deprecated and deactivated linters
  #- exhaustivestruct
  #- golint
  #- ifshort
  #- interfacer
  #- maligned
  #- scopelint
  #- nosnakecase
  #- structcheck
  #- deadcode
  #- varcheck
  #
  # Disable deprecated linters
  - execinquery
  - gomnd
  - exportloopref
  # Disabled to test private functions
  - testpackage
  # Allow to use global variables
  - gochecknoglobals
  # Allow camel-cased tags in struct tags
  - tagliatelle

linters-settings:
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          # Standard go packages
          - $gostd
          # Required for testing
          - github.com/stretchr/testify
          - github.com/KEINOS/go-md-spec-check/mdspec
          # Deprecated but still using for easy error handling
          - github.com/pkg/errors
