run:
  tests: true
  fast: true
  build-tags:
    - golangci
  skip-dirs:
    - .github
  allow-parallel-runners: true

output:
  format: colored-line-number
  sort-results: true

linters:
  enable-all: true
  disable:
  # Deprecated linters
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - maligned
  - scopelint
  - nosnakecase
  - structcheck
  - deadcode
  - varcheck
  # Disabled to test private functions
  - testpackage
  # Allow to use global variables
  - gochecknoglobals
  # Allow camel-cased tags in struct tags
  - tagliatelle

linters-settings:
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          # Standard go packages
          - $gostd
          # Required for testing
          - github.com/stretchr/testify
          - github.com/KEINOS/go-md-spec-check/mdspec
          # Deprecated but still using for easy error handling
          - github.com/pkg/errors
