# =============================================================================
# Docker Compose file for testing on Go versions 1.18 to the latest.
# =============================================================================
# Usage:
#     $ # Build all the containers
#     $ docker compose build
#
#     $ # Run lint check/static analysis with golangci-lint
#     $ docker compose run --rm lint
#
#     $ # Run unit tests on Go 1.18
#     $ docker compose run --rm v1_18
#
#     $ # Run unit tests on latest Go version
#     $ docker compose run --rm latest
volumes:
  GO_PKG_MOD:

services:
  # run latest golangci-lint
  lint:
    image: golangci/golangci-lint:latest
    working_dir: /workspaces
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod
    entrypoint: golangci-lint run
  # Service tidy updates the go.mod to the latest
  tidy:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.18-alpine
    volumes:
      - .:/workspaces
    entrypoint: [ "./.github/run_go_mod_tidy.sh" ]
  # Service mil runs the tests on minimum supported Go version
  min:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.18-alpine
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod
  # Service latest runs the tests on latest Go docker image
  latest:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod